### ISSUE TITLE
interesting... can I ask what your plans are with this project?

### ISSUE THREAD

**Issue by luizcmarin** [VHNam1507/LangSkillz#1]
interesting... can I ask what your plans are with this project?

**Comment by VHNam1507** [comment]
> interesting... can I ask what your plans are with this project?


Well, actually this is a project for my university course. I plan to build an online learning website using ASP.NET.
With the website I am building, users can play the role of either an Instructor or a Student. Instructors will be able to create courses and lessons within those courses, and each lesson will have multiple-choice questions. Students will be able to enroll in courses built by Instructors. By registering for a course, Students will be able to view lesson content and answer the multiple-choice questions within the courses they have enrolled in.

"LangSkillz" here is a hypothetical name for any organization using the website I build for language teaching. Furthermore, for language learning, we have 4 skills to focus on, namely "LISTENING, SPEAKING, READING, AND WRITING" so creating a variety of question types will also be a problem to solve (for example, for listening and reading skills, multiple-choice questions will be used, while for writing skills, essay questions will be used, and for speaking skills, audio questions will be used where Students will have to record their answers).

Well, in general, these are all just plans and goals that I am aiming for. But for now, I will complete this online learning website prototype by focusing on multiple-choice questions, student course management, and database manipulation to avoid conflicts.

**Comment by luizcmarin** [comment]
an excellent project. Too bad it's in ASP.... if it was PHP maybe I could participate
